name: cd

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Build app
        run: npm run build

       # ✅ NEW: Authenticate with GCP (THIS FIXES YOUR ERROR)
      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      # ✅ Setup gcloud (no auth here anymore)
      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: notely-491205

      # ✅ Build & push Docker image
      - name: Build and push Docker image
        run: |
          gcloud builds submit \
            --tag us-central1-docker.pkg.dev/notely-491205/notely-ar-repo/notely:latest